Conditional PWR signal for macos
The current PWR signal inclusion causes build errors as its not available on darwin builds.

# github.com/hashicorp/nomad-driver-exec2/pkg/resources/process
../../../go/pkg/mod/github.com/hashicorp/nomad-driver-exec2@v0.1.0/pkg/resources/process/signal.go:43:18: undefined: syscall.SIGPWR
(base) deanhunter@Mac test % go build